# -*- coding: utf-8 -*-
#
import sys, os
#
import sphinx_rtd_theme
#
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('.'))
# sys.path.insert(0, os.path.abspath(os.path.join('..', 'exts'))) ajouterait un répertoire situé au dessus " '..' " et dénommé "ext"
sys.path.insert(0, os.path.abspath(os.path.join('_extensions')))
#
#import recommonmark.parser (insertion documents avec syntaxe Markdown)
from recommonmark.parser import CommonMarkParser
from recommonmark.transform import AutoStructify


# -- General configuration ------------------------------------------------

# local var only, from Blender docs
doc_version = "1.02"

rst_epilog = """
.. |doc_version| replace:: %s
""" % doc_version

# include at end of every file
rst_epilog = """
.. substitutions
.. |OTU| replace:: *Olivier TURLIER*
.. |MAR| replace:: **Marc ARMSPACH**

.. |acad| replace:: **AutoCAD**
.. |rst| replace:: **reStructuredText**
.. |site| replace:: site Internet

.. |cms| replace:: :abbr:`CMS (Content Management System)`
.. |dita-ot| replace:: :abbr:`DITA-OT (DITA Open Toolkit)`
.. |github| replace:: *GitHub*
.. |git| replace:: *Git*
.. |gui| replace:: :abbr:`GUI (Graphical User Interface)`
.. |ide| replace:: :abbr:`IDE (Integrated Development Environment)`
.. |latex| replace:: *LaTeX*
.. |sphinx| replace:: Python Sphinx
.. |ssh| replace:: :abbr:`SSH (Secure Shell)`

.. links
.. _Linkedin: http://www.linkedin.com
.. _Autodesk: http://www.autodesk.fr/
"""



# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
#    'ablog',
    'sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    # from reauthoring docs, for learning stuff
    # all those extensions are located in _extension dir, accessible via "sys_path_insert ..." supra
    # '_extensions.activity_duration',
    # '_extensions.html_form',
    # '_extensions.instructor_feedback',
    # '_extensions.eqt',
    # '_extensions.instructor_guide',
    # '_extensions.embedded_video',
    # '_extensions.xy_click',
    # '_extensions.questions',
    # '_extensions.iframe',
    ## from Blender docs
    'youtube',
    'vimeo'
    ]

# # blog stuff
# blog_baseurl = 'http://www.canopee.org/blog/'
# blog_path = 'blog/archive'
# blog_authors = {
#     'Team': ('Canopée Team', 'http://www.canopee.org/team/'),
#     'Oli': ('Olivier Turlier', 'http://ericholscher.com'),
#     'Ant': ('Anthony Johnson', 'http://ohess.org'),
# }
# blog_default_author = 'Team'
#
# blog_languages = {
#     'fr': ('French', None),
# }
#
# blog_locations = {
#     'TLS': ('Toulouse, Occitanie', 'http://www.laregionoccitanie.fr//'),
# }
#
# blog_default_location = 'TLS'
# fontawesome_link_cdn = 'http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css'
#
# templates_path = ['_templates']
#templates_path.append(ablog.get_html_templates_path())


# Math
mathjax_path = "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
# # like Kinto index page
# html_additional_pages = {
#     'index': 'indexcontent.html',
# }


#Markdown support
source_parsers = {
    '.md': 'recommonmark.parser.CommonMarkParser',
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Doc AutoCAD'
copyright = u'2001-2017, Olivier TURLIER, http://canopee.org/ '
author = u'Canopee Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = doc_version
# The full version, including alpha/beta/rc tags.
release = doc_version

del doc_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    'docs/testdocs/geek-docs/*',
    '../old/*'
    '_extensions/_templates/*.rst',
    '_themes/*.rst',
    '_themes/*.md'
]

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
show_authors = True


# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

today_fmt = '%d %m %Y'

# -- Options for HTML output ----------------------------------------------

## The theme to use for HTML and HTML Help pages.  See the documentation for
## a list of builtin themes.
##
#
html_theme = 'sphinx_rtd_theme'
# #
html_theme_options = {
    # included in the title
    "display_version": False,
    }
# #
#
#
html_theme_path = ['_themes']
#
#html_theme = 't3SphinxThemeRtd'
#
html_title = "Docs Canopee"
# #
html_logo = "_static/logo.png"
# #
html_favicon = "_static/canopee_ico.ico"
# #
html_context = {
    'css_files': [
        '_static/css/theme-overrides.css',
        #_static/css/custom_theme.css',  # overrides wide tables in RTD theme
#        '_static/bespoke.css',  # custom CSS styling
#        '_static/bolditalic.css',  # bolditalic styling
        ],
}
#html_context = {'css_files':['_static/css/theme_overrides.css],}
#
## equivs to
#
## def setup(app):
##    app.add_stylesheet("css/theme_overrides.css")
#
# or ?
#
# app.add_stylesheet('css/custom_theme.css') # path relative to _static
#

# MAIN_SITE = '//canopee.org'
#
# html_context = {
#     'SITEMAP_BASE_URL': 'http://canopee.org/', # Trailing slash is needed
#     'DESCRIPTION': 'Site documentation sur logiciels DAO.',
#     'AUTHOR': 'Equipe Canopée',
#     'VERSION': 1.01,
#     # Nav
#     'NAV': (
#         ('A-propos', MAIN_SITE + '/pages/about-bokeh.html'),
#         ('News', '/docs/gallery.html'),
#         ('Docs', '//bokeh.pydata.org/en/latest/'),
#         ('Github', '//github.com/bokeh/bokeh'),
#     ),
#     # Links
#     'LINKS': (
#         ('FAQs', MAIN_SITE + '/pages/faqs.html'),
#         ('Technical vision', MAIN_SITE + '/pages/technical-vision.html'),
#         ('Roadmap', MAIN_SITE + '/pages/roadmap.html'),
#         ('Citation', MAIN_SITE + '/pages/citation.html'),
#     ),
#     # About Links
#     'ABOUT': (
#         ('A propos', MAIN_SITE + '/pages/about-bokeh.html'),
#         ('Equipe', MAIN_SITE + '/pages/team.html'),
#         ('Contact', MAIN_SITE + '/pages/contact.html'),
#     ),
#     # Social links
#     'SOCIAL': (
#         ('Contribute', MAIN_SITE + '/pages/contribute.html'),
# #        ('Mailing list', '//groups.google.com/a/continuum.io/forum/#!forum/bokeh'),
#         ('Github', '//github.com/olitur/canopee-docs'),
#         ('Twitter', '//twitter.com/antropyk'),
# #        ('YouTube', '//www.youtube.com/channel/UCK0rSk29mmg4UT4bIOvPYhw')
#     ),
#     # Links for the docs sub navigation
#     'NAV_DOCS': (
#         ('Sketchup', 'sketchup'),
#         ('AutoCAD', 'autocad'),
#         ('Rhino', 'rhino'),
#         ('Grasshopper', 'grasshopper'), # too much links ?
#         ('Revit', 'revit'),
#         ('Dynamo', 'dynamo'),
#     ),
# #    'ALL_VERSIONS': all_versions,
# #    'css_server': os.environ.get('BOKEH_DOCS_CSS_SERVER', 'bokehplots.com'),
# }
#

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = ["_static/404.html"]
html_extra_path = ['_static/extra/']

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Remove permalinks "P" at ends of each title
#
html_add_permalinks = False

# If false, no index is generated.
#
html_use_index = False

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
html_show_sourcelink = False

# Remove copying of source
#
html_copy_source = False

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#
html_search_language = 'fr'

#
# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Canopee Docs AutoCAD'


# -- Options for LaTeX output ---------------------------------------------

# latex_elements = {
#     # The paper size ('letterpaper' or 'a4paper').
#     #
#     'papersize': 'a4paper',
#     # The font size ('10pt', '11pt' or '12pt').
#     #
#     'pointsize': '12pt',
#     # Additional stuff for the LaTeX preamble.
#     #
# #     'preamble': r'\usepackage{odoostyle}',
# #     'preamble': '\\usepackage{strat}',
# #    'fontpkg': '\\usepackage[defaultsans]{droidsans}\n\\renewcommand*\\familydefault{\\sfdefault}',
#      'fontpkg': r'\usepackage{mathpazo}',
# #    'fontpkg': '\\usepackage{mnsymbol}\n\\renewcommand*\\familydefault{\\sfdefault}',
#
# #    'fncychap': '',
#     'preamble': r'\usepackage{flaskstyle}',
#     # Latex figure (float) alignment
#     #
#     #'figure_align': 'htbp',
# }
#
# # Grouping the document tree into LaTeX files. List of tuples
# # (source start file, target name, title,author, documentclass [howto, manual, or own class]).
# latex_documents = [
# #    (master_doc, 'rtd.tex', u'rtd+ Documentation', u'olitur', 'manual'),
# #    ('docs/sketchup', 'sketchup.tex', 'Documentation Sketchup', 'olitur', 'manual'),
#     ('docs/tuts/index', 'acad-tuts.tex', 'Tutoriels AutoCAD', 'olitur', 'manual'),
#     ('docs/guides/index', 'acad-guides.tex', 'Guides AutoCAD', 'olitur', 'manual'),
#     ('docs/refs/index', 'acad-refs.tex', 'Références AutoCAD', 'olitur', 'manual')
# ]
# #
# latex_additional_files = ['_static/latex/flaskstyle.sty', '_static/latex/canopee_logo.pdf',
# '_static/latex/canopee-sidebarlogo.png']
# #'_static/latex/odoostyle.sty', '_static/latex/strat.sty',
# #
# # # The name of an image file (relative to this directory) to place at the top of
# # # the title page.
# latex_logo = '_static/latex/canopee_logo.pdf'
# # ##
#
# # For "manual" documents, if this is true, then toplevel headings are parts,
# # not chapters.
# latex_use_parts = False
#
# # If true, add page references after internal references. This is very useful for
# # printed copies of the manual. Default is False.
# latex_show_pagerefs = True
#
# # Control whether to display URL addresses. The setting can have the following values:
# # 'no' – do not display URLs (default)
# # 'footnote' – display URLs in footnotes
# # 'inline' – display URLs inline in parentheses
# latex_show_urls = 'footnote' # 'inline'

# test from sphinx-doc itself ...
latex_engine = 'xelatex'
# latex_elements = {
#    'papersize': 'a4paper',
#   'fontenc': '\\usepackage{fontspec}',
#   'fontpkg': '''\
# \\setmainfont{DejaVu Serif}
# \\setsansfont{DejaVu Sans}
# \\setmonofont{DejaVu Sans Mono}''',
#   'geometry': '\\usepackage[vmargin=2cm, hmargin=2cm]{geometry}',
#   'preamble': '''\
# \\PassOptionsToPackage{dvipsnames,table,xcdraw,svgnames}{xcolor}
# \\usepackage{sectsty}
# \\sphinxsetup{%
# verbatimwithframe=false,
# VerbatimColor={named}{lightgray},
# TitleColor={named}{BrickRed},
# hintBorderColor={named}{lightgray},
# attentionborder=3pt,
# attentionBorderColor={named}{lightgray},
# attentionBgColor={named}{teal},
# noteborder=2pt,
# noteBorderColor={named}{orange},
# cautionborder=3pt,
# cautionBorderColor={named}{Maroon},
# cautionBgColor={named}{GreenYellow}}
# \\usepackage[titles]{tocloft}
# \\cftsetpnumwidth {1.25cm}\\cftsetrmarg{1.5cm}
# \\setlength{\\cftchapnumwidth}{0.75cm}
# \\setlength{\\cftsecindent}{\\cftchapnumwidth}
# \\setlength{\\cftsecnumwidth}{1.25cm}''',
#   'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
#   'printindex': '\\footnotesize\\raggedright\\printindex',
# }
latex_elements = {
  'papersize': 'a4paper',
  'fontenc': '\\usepackage{fontspec}',
  'fontpkg': '''\
\\PassOptionsToPackage{dvipsnames,table,xcdraw,svgnames}{xcolor}
\\setmainfont{DejaVu Serif}
\\setsansfont{DejaVu Sans}
\\setmonofont{DejaVu Sans Mono}''',
  'geometry': '\\usepackage[vmargin=2.5cm, hmargin=3cm]{geometry}',
  'preamble': '''\
\\sphinxsetup{%
    verbatimwithframe=false,
    VerbatimColor={named}{OldLace},
    TitleColor={named}{DarkGoldenrod},
    hintBorderColor={named}{LightCoral},
    attentionborder=3pt,
    attentionBorderColor={named}{Crimson},
    attentionBgColor={named}{FloralWhite},
    noteborder=2pt,
    noteBorderColor={named}{Olive},
    cautionborder=3pt,
    cautionBorderColor={named}{Cyan},
    cautionBgColor={named}{LightCyan}}
\\usepackage[titles]{tocloft}
\\cftsetpnumwidth {1.25cm}\\cftsetrmarg{1.5cm}
\\setlength{\\cftchapnumwidth}{0.75cm}
\\setlength{\\cftsecindent}{\\cftchapnumwidth}
\\setlength{\\cftsecnumwidth}{1.25cm}''',
  'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
  'printindex': '\\footnotesize\\raggedright\\printindex',
}
latex_show_urls = 'footnote'
latex_use_parts = False
latex_show_pagerefs = True
latex_logo = '_static/latex/canopee_logo.pdf'
latex_additional_files = ['_static/latex/canopee_logo.pdf','_static/latex/canopee-sidebarlogo.png']
#'_static/latex/odoostyle.sty', '_static/latex/strat.sty',
latex_documents = [
#    (master_doc, 'rtd.tex', u'rtd+ Documentation', u'olitur', 'manual'),
#    ('docs/sketchup', 'sketchup.tex', 'Documentation Sketchup', 'olitur', 'manual'),
    ('docs/tuts/index', 'acad-tuts.tex', 'Tutoriels AutoCAD', 'olitur', 'manual'),
    ('docs/guides/index', 'acad-guides.tex', 'Guides AutoCAD', 'olitur', 'manual'),
    ('docs/refs/index', 'acad-refs.tex', 'Références AutoCAD', 'olitur', 'manual')
]


# Additional stuff for the LaTeX preamble.
# NOTE!
#
# This LaTeX preamble overrides some Sphinx/LaTeX defaults in order to make
# better output.  This comment will try to explain what's going on here.
# These hacks were perpetrated by Mike and Jeff.
#
# 0. Set Helvetica as default font
#	See the \\usepackage[scaled]{helvet} command
# 1. Resize images so that they are no wider than 4in.
#      Accomplished by renewing the \includegraphics command, and creating an
#      if/then statement saying to resize to 4in if large than 4in, otherwise
#      leave alone
#      (The Suite logo on the title page is not given a dropshadow.)
# 2. Add drop shadow to images
#      Accomplished by wrapping the above imcludegraphics commands with a
#      \shadowbox.  Default border and spacing are changed in the \setlength
#      commands
# 3. Force LaTeX to place the images inline
#      For whatever reason, Sphinx automatically appends the \begin{figure}
#      command with [htbp], which means "put the figure where ever you feel
#      like it."  We replaced the command to be appended with [H], which
#      means "put the figure right here".  Unfortunately, this caused the
#      [htbp] text to become visible in the document.  Thus we added the
#      [6], to eat up the 6 characters, which, due to placement, would be
#      taken as arguments.
# 4. Change to a.b.c.d section numbering
#      \setcounter{secnumdepth}{3}
# 5. Include a.b.c sections in TOC
#      \setcounter{tocdepth}{2}
# 6. Enable line breaking in code
#      \lstset
# 7. Remove blank pages
#    \let\cleardoublepage\clearpage
# 8. Add Boundless Suite logo to some headers
#    \fancyhead
# 9. Remove headers in 8. from the title page
#    \pagestyle{empty}
#


# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_use_modindex = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'acad', 'Documentation AutoCAD',
     [''], 1)
]

# If true, show URL addresses after external links.
man_show_urls = False

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'rtd', u'rtd+ Documentation',
     author, 'rtd', 'One line description of project.',
     'Miscellaneous')
]
